



#if ENABLE_UNITY_MATHEMATICS

namespace Blob.Mathematics
{

    [DefaultBuilder] public class bool2Builder : Blob.ValueBuilder<Unity.Mathematics.bool2> {}
    [DefaultBuilder] public class bool2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool2> {}
    [DefaultBuilder] public class bool2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.bool2> {}
    [DefaultBuilder] public class bool2x2Builder : Blob.ValueBuilder<Unity.Mathematics.bool2x2> {}
    [DefaultBuilder] public class bool2x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool2x2> {}
    [DefaultBuilder] public class bool2x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.bool2x2> {}
    [DefaultBuilder] public class bool2x3Builder : Blob.ValueBuilder<Unity.Mathematics.bool2x3> {}
    [DefaultBuilder] public class bool2x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool2x3> {}
    [DefaultBuilder] public class bool2x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.bool2x3> {}
    [DefaultBuilder] public class bool2x4Builder : Blob.ValueBuilder<Unity.Mathematics.bool2x4> {}
    [DefaultBuilder] public class bool2x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool2x4> {}
    [DefaultBuilder] public class bool2x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.bool2x4> {}
    [DefaultBuilder] public class bool3Builder : Blob.ValueBuilder<Unity.Mathematics.bool3> {}
    [DefaultBuilder] public class bool3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool3> {}
    [DefaultBuilder] public class bool3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.bool3> {}
    [DefaultBuilder] public class bool3x2Builder : Blob.ValueBuilder<Unity.Mathematics.bool3x2> {}
    [DefaultBuilder] public class bool3x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool3x2> {}
    [DefaultBuilder] public class bool3x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.bool3x2> {}
    [DefaultBuilder] public class bool3x3Builder : Blob.ValueBuilder<Unity.Mathematics.bool3x3> {}
    [DefaultBuilder] public class bool3x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool3x3> {}
    [DefaultBuilder] public class bool3x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.bool3x3> {}
    [DefaultBuilder] public class bool3x4Builder : Blob.ValueBuilder<Unity.Mathematics.bool3x4> {}
    [DefaultBuilder] public class bool3x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool3x4> {}
    [DefaultBuilder] public class bool3x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.bool3x4> {}
    [DefaultBuilder] public class bool4Builder : Blob.ValueBuilder<Unity.Mathematics.bool4> {}
    [DefaultBuilder] public class bool4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool4> {}
    [DefaultBuilder] public class bool4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.bool4> {}
    [DefaultBuilder] public class bool4x2Builder : Blob.ValueBuilder<Unity.Mathematics.bool4x2> {}
    [DefaultBuilder] public class bool4x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool4x2> {}
    [DefaultBuilder] public class bool4x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.bool4x2> {}
    [DefaultBuilder] public class bool4x3Builder : Blob.ValueBuilder<Unity.Mathematics.bool4x3> {}
    [DefaultBuilder] public class bool4x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool4x3> {}
    [DefaultBuilder] public class bool4x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.bool4x3> {}
    [DefaultBuilder] public class bool4x4Builder : Blob.ValueBuilder<Unity.Mathematics.bool4x4> {}
    [DefaultBuilder] public class bool4x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool4x4> {}
    [DefaultBuilder] public class bool4x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.bool4x4> {}
    [DefaultBuilder] public class double2Builder : Blob.ValueBuilder<Unity.Mathematics.double2> {}
    [DefaultBuilder] public class double2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double2> {}
    [DefaultBuilder] public class double2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.double2> {}
    [DefaultBuilder] public class double2x2Builder : Blob.ValueBuilder<Unity.Mathematics.double2x2> {}
    [DefaultBuilder] public class double2x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double2x2> {}
    [DefaultBuilder] public class double2x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.double2x2> {}
    [DefaultBuilder] public class double2x3Builder : Blob.ValueBuilder<Unity.Mathematics.double2x3> {}
    [DefaultBuilder] public class double2x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double2x3> {}
    [DefaultBuilder] public class double2x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.double2x3> {}
    [DefaultBuilder] public class double2x4Builder : Blob.ValueBuilder<Unity.Mathematics.double2x4> {}
    [DefaultBuilder] public class double2x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double2x4> {}
    [DefaultBuilder] public class double2x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.double2x4> {}
    [DefaultBuilder] public class double3Builder : Blob.ValueBuilder<Unity.Mathematics.double3> {}
    [DefaultBuilder] public class double3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double3> {}
    [DefaultBuilder] public class double3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.double3> {}
    [DefaultBuilder] public class double3x2Builder : Blob.ValueBuilder<Unity.Mathematics.double3x2> {}
    [DefaultBuilder] public class double3x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double3x2> {}
    [DefaultBuilder] public class double3x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.double3x2> {}
    [DefaultBuilder] public class double3x3Builder : Blob.ValueBuilder<Unity.Mathematics.double3x3> {}
    [DefaultBuilder] public class double3x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double3x3> {}
    [DefaultBuilder] public class double3x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.double3x3> {}
    [DefaultBuilder] public class double3x4Builder : Blob.ValueBuilder<Unity.Mathematics.double3x4> {}
    [DefaultBuilder] public class double3x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double3x4> {}
    [DefaultBuilder] public class double3x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.double3x4> {}
    [DefaultBuilder] public class double4Builder : Blob.ValueBuilder<Unity.Mathematics.double4> {}
    [DefaultBuilder] public class double4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double4> {}
    [DefaultBuilder] public class double4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.double4> {}
    [DefaultBuilder] public class double4x2Builder : Blob.ValueBuilder<Unity.Mathematics.double4x2> {}
    [DefaultBuilder] public class double4x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double4x2> {}
    [DefaultBuilder] public class double4x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.double4x2> {}
    [DefaultBuilder] public class double4x3Builder : Blob.ValueBuilder<Unity.Mathematics.double4x3> {}
    [DefaultBuilder] public class double4x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double4x3> {}
    [DefaultBuilder] public class double4x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.double4x3> {}
    [DefaultBuilder] public class double4x4Builder : Blob.ValueBuilder<Unity.Mathematics.double4x4> {}
    [DefaultBuilder] public class double4x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double4x4> {}
    [DefaultBuilder] public class double4x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.double4x4> {}
    [DefaultBuilder] public class float2Builder : Blob.ValueBuilder<Unity.Mathematics.float2> {}
    [DefaultBuilder] public class float2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float2> {}
    [DefaultBuilder] public class float2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.float2> {}
    [DefaultBuilder] public class float2x2Builder : Blob.ValueBuilder<Unity.Mathematics.float2x2> {}
    [DefaultBuilder] public class float2x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float2x2> {}
    [DefaultBuilder] public class float2x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.float2x2> {}
    [DefaultBuilder] public class float2x3Builder : Blob.ValueBuilder<Unity.Mathematics.float2x3> {}
    [DefaultBuilder] public class float2x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float2x3> {}
    [DefaultBuilder] public class float2x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.float2x3> {}
    [DefaultBuilder] public class float2x4Builder : Blob.ValueBuilder<Unity.Mathematics.float2x4> {}
    [DefaultBuilder] public class float2x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float2x4> {}
    [DefaultBuilder] public class float2x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.float2x4> {}
    [DefaultBuilder] public class float3Builder : Blob.ValueBuilder<Unity.Mathematics.float3> {}
    [DefaultBuilder] public class float3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float3> {}
    [DefaultBuilder] public class float3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.float3> {}
    [DefaultBuilder] public class float3x2Builder : Blob.ValueBuilder<Unity.Mathematics.float3x2> {}
    [DefaultBuilder] public class float3x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float3x2> {}
    [DefaultBuilder] public class float3x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.float3x2> {}
    [DefaultBuilder] public class float3x3Builder : Blob.ValueBuilder<Unity.Mathematics.float3x3> {}
    [DefaultBuilder] public class float3x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float3x3> {}
    [DefaultBuilder] public class float3x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.float3x3> {}
    [DefaultBuilder] public class float3x4Builder : Blob.ValueBuilder<Unity.Mathematics.float3x4> {}
    [DefaultBuilder] public class float3x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float3x4> {}
    [DefaultBuilder] public class float3x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.float3x4> {}
    [DefaultBuilder] public class float4Builder : Blob.ValueBuilder<Unity.Mathematics.float4> {}
    [DefaultBuilder] public class float4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float4> {}
    [DefaultBuilder] public class float4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.float4> {}
    [DefaultBuilder] public class float4x2Builder : Blob.ValueBuilder<Unity.Mathematics.float4x2> {}
    [DefaultBuilder] public class float4x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float4x2> {}
    [DefaultBuilder] public class float4x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.float4x2> {}
    [DefaultBuilder] public class float4x3Builder : Blob.ValueBuilder<Unity.Mathematics.float4x3> {}
    [DefaultBuilder] public class float4x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float4x3> {}
    [DefaultBuilder] public class float4x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.float4x3> {}
    [DefaultBuilder] public class float4x4Builder : Blob.ValueBuilder<Unity.Mathematics.float4x4> {}
    [DefaultBuilder] public class float4x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float4x4> {}
    [DefaultBuilder] public class float4x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.float4x4> {}
    [DefaultBuilder] public class halfBuilder : Blob.ValueBuilder<Unity.Mathematics.half> {}
    [DefaultBuilder] public class halfArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.half> {}
    [DefaultBuilder] public class halfPtrBuilder : Blob.PtrBuilder<Unity.Mathematics.half> {}
    [DefaultBuilder] public class half2Builder : Blob.ValueBuilder<Unity.Mathematics.half2> {}
    [DefaultBuilder] public class half2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.half2> {}
    [DefaultBuilder] public class half2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.half2> {}
    [DefaultBuilder] public class half3Builder : Blob.ValueBuilder<Unity.Mathematics.half3> {}
    [DefaultBuilder] public class half3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.half3> {}
    [DefaultBuilder] public class half3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.half3> {}
    [DefaultBuilder] public class half4Builder : Blob.ValueBuilder<Unity.Mathematics.half4> {}
    [DefaultBuilder] public class half4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.half4> {}
    [DefaultBuilder] public class half4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.half4> {}
    [DefaultBuilder] public class int2Builder : Blob.ValueBuilder<Unity.Mathematics.int2> {}
    [DefaultBuilder] public class int2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int2> {}
    [DefaultBuilder] public class int2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.int2> {}
    [DefaultBuilder] public class int2x2Builder : Blob.ValueBuilder<Unity.Mathematics.int2x2> {}
    [DefaultBuilder] public class int2x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int2x2> {}
    [DefaultBuilder] public class int2x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.int2x2> {}
    [DefaultBuilder] public class int2x3Builder : Blob.ValueBuilder<Unity.Mathematics.int2x3> {}
    [DefaultBuilder] public class int2x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int2x3> {}
    [DefaultBuilder] public class int2x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.int2x3> {}
    [DefaultBuilder] public class int2x4Builder : Blob.ValueBuilder<Unity.Mathematics.int2x4> {}
    [DefaultBuilder] public class int2x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int2x4> {}
    [DefaultBuilder] public class int2x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.int2x4> {}
    [DefaultBuilder] public class int3Builder : Blob.ValueBuilder<Unity.Mathematics.int3> {}
    [DefaultBuilder] public class int3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int3> {}
    [DefaultBuilder] public class int3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.int3> {}
    [DefaultBuilder] public class int3x2Builder : Blob.ValueBuilder<Unity.Mathematics.int3x2> {}
    [DefaultBuilder] public class int3x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int3x2> {}
    [DefaultBuilder] public class int3x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.int3x2> {}
    [DefaultBuilder] public class int3x3Builder : Blob.ValueBuilder<Unity.Mathematics.int3x3> {}
    [DefaultBuilder] public class int3x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int3x3> {}
    [DefaultBuilder] public class int3x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.int3x3> {}
    [DefaultBuilder] public class int3x4Builder : Blob.ValueBuilder<Unity.Mathematics.int3x4> {}
    [DefaultBuilder] public class int3x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int3x4> {}
    [DefaultBuilder] public class int3x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.int3x4> {}
    [DefaultBuilder] public class int4Builder : Blob.ValueBuilder<Unity.Mathematics.int4> {}
    [DefaultBuilder] public class int4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int4> {}
    [DefaultBuilder] public class int4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.int4> {}
    [DefaultBuilder] public class int4x2Builder : Blob.ValueBuilder<Unity.Mathematics.int4x2> {}
    [DefaultBuilder] public class int4x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int4x2> {}
    [DefaultBuilder] public class int4x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.int4x2> {}
    [DefaultBuilder] public class int4x3Builder : Blob.ValueBuilder<Unity.Mathematics.int4x3> {}
    [DefaultBuilder] public class int4x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int4x3> {}
    [DefaultBuilder] public class int4x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.int4x3> {}
    [DefaultBuilder] public class int4x4Builder : Blob.ValueBuilder<Unity.Mathematics.int4x4> {}
    [DefaultBuilder] public class int4x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int4x4> {}
    [DefaultBuilder] public class int4x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.int4x4> {}
    [DefaultBuilder] public class quaternionBuilder : Blob.ValueBuilder<Unity.Mathematics.quaternion> {}
    [DefaultBuilder] public class quaternionArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.quaternion> {}
    [DefaultBuilder] public class quaternionPtrBuilder : Blob.PtrBuilder<Unity.Mathematics.quaternion> {}
    [DefaultBuilder] public class RandomBuilder : Blob.ValueBuilder<Unity.Mathematics.Random> {}
    [DefaultBuilder] public class RandomArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.Random> {}
    [DefaultBuilder] public class RandomPtrBuilder : Blob.PtrBuilder<Unity.Mathematics.Random> {}
    [DefaultBuilder] public class RigidTransformBuilder : Blob.ValueBuilder<Unity.Mathematics.RigidTransform> {}
    [DefaultBuilder] public class RigidTransformArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.RigidTransform> {}
    [DefaultBuilder] public class RigidTransformPtrBuilder : Blob.PtrBuilder<Unity.Mathematics.RigidTransform> {}
    [DefaultBuilder] public class uint2Builder : Blob.ValueBuilder<Unity.Mathematics.uint2> {}
    [DefaultBuilder] public class uint2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint2> {}
    [DefaultBuilder] public class uint2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.uint2> {}
    [DefaultBuilder] public class uint2x2Builder : Blob.ValueBuilder<Unity.Mathematics.uint2x2> {}
    [DefaultBuilder] public class uint2x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint2x2> {}
    [DefaultBuilder] public class uint2x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.uint2x2> {}
    [DefaultBuilder] public class uint2x3Builder : Blob.ValueBuilder<Unity.Mathematics.uint2x3> {}
    [DefaultBuilder] public class uint2x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint2x3> {}
    [DefaultBuilder] public class uint2x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.uint2x3> {}
    [DefaultBuilder] public class uint2x4Builder : Blob.ValueBuilder<Unity.Mathematics.uint2x4> {}
    [DefaultBuilder] public class uint2x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint2x4> {}
    [DefaultBuilder] public class uint2x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.uint2x4> {}
    [DefaultBuilder] public class uint3Builder : Blob.ValueBuilder<Unity.Mathematics.uint3> {}
    [DefaultBuilder] public class uint3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint3> {}
    [DefaultBuilder] public class uint3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.uint3> {}
    [DefaultBuilder] public class uint3x2Builder : Blob.ValueBuilder<Unity.Mathematics.uint3x2> {}
    [DefaultBuilder] public class uint3x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint3x2> {}
    [DefaultBuilder] public class uint3x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.uint3x2> {}
    [DefaultBuilder] public class uint3x3Builder : Blob.ValueBuilder<Unity.Mathematics.uint3x3> {}
    [DefaultBuilder] public class uint3x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint3x3> {}
    [DefaultBuilder] public class uint3x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.uint3x3> {}
    [DefaultBuilder] public class uint3x4Builder : Blob.ValueBuilder<Unity.Mathematics.uint3x4> {}
    [DefaultBuilder] public class uint3x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint3x4> {}
    [DefaultBuilder] public class uint3x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.uint3x4> {}
    [DefaultBuilder] public class uint4Builder : Blob.ValueBuilder<Unity.Mathematics.uint4> {}
    [DefaultBuilder] public class uint4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint4> {}
    [DefaultBuilder] public class uint4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.uint4> {}
    [DefaultBuilder] public class uint4x2Builder : Blob.ValueBuilder<Unity.Mathematics.uint4x2> {}
    [DefaultBuilder] public class uint4x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint4x2> {}
    [DefaultBuilder] public class uint4x2PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.uint4x2> {}
    [DefaultBuilder] public class uint4x3Builder : Blob.ValueBuilder<Unity.Mathematics.uint4x3> {}
    [DefaultBuilder] public class uint4x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint4x3> {}
    [DefaultBuilder] public class uint4x3PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.uint4x3> {}
    [DefaultBuilder] public class uint4x4Builder : Blob.ValueBuilder<Unity.Mathematics.uint4x4> {}
    [DefaultBuilder] public class uint4x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint4x4> {}
    [DefaultBuilder] public class uint4x4PtrBuilder : Blob.PtrBuilder<Unity.Mathematics.uint4x4> {}

}

#endif

