

#if ENABLE_UNITY_MATHEMATICS

namespace Blob.Mathematics
{

    public class bool2Builder : Blob.DefaultBuilder<Unity.Mathematics.bool2> {}
    public class bool2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool2> {}
    public class bool2x2Builder : Blob.DefaultBuilder<Unity.Mathematics.bool2x2> {}
    public class bool2x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool2x2> {}
    public class bool2x3Builder : Blob.DefaultBuilder<Unity.Mathematics.bool2x3> {}
    public class bool2x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool2x3> {}
    public class bool2x4Builder : Blob.DefaultBuilder<Unity.Mathematics.bool2x4> {}
    public class bool2x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool2x4> {}
    public class bool3Builder : Blob.DefaultBuilder<Unity.Mathematics.bool3> {}
    public class bool3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool3> {}
    public class bool3x2Builder : Blob.DefaultBuilder<Unity.Mathematics.bool3x2> {}
    public class bool3x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool3x2> {}
    public class bool3x3Builder : Blob.DefaultBuilder<Unity.Mathematics.bool3x3> {}
    public class bool3x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool3x3> {}
    public class bool3x4Builder : Blob.DefaultBuilder<Unity.Mathematics.bool3x4> {}
    public class bool3x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool3x4> {}
    public class bool4Builder : Blob.DefaultBuilder<Unity.Mathematics.bool4> {}
    public class bool4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool4> {}
    public class bool4x2Builder : Blob.DefaultBuilder<Unity.Mathematics.bool4x2> {}
    public class bool4x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool4x2> {}
    public class bool4x3Builder : Blob.DefaultBuilder<Unity.Mathematics.bool4x3> {}
    public class bool4x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool4x3> {}
    public class bool4x4Builder : Blob.DefaultBuilder<Unity.Mathematics.bool4x4> {}
    public class bool4x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.bool4x4> {}
    public class double2Builder : Blob.DefaultBuilder<Unity.Mathematics.double2> {}
    public class double2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double2> {}
    public class double2x2Builder : Blob.DefaultBuilder<Unity.Mathematics.double2x2> {}
    public class double2x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double2x2> {}
    public class double2x3Builder : Blob.DefaultBuilder<Unity.Mathematics.double2x3> {}
    public class double2x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double2x3> {}
    public class double2x4Builder : Blob.DefaultBuilder<Unity.Mathematics.double2x4> {}
    public class double2x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double2x4> {}
    public class double3Builder : Blob.DefaultBuilder<Unity.Mathematics.double3> {}
    public class double3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double3> {}
    public class double3x2Builder : Blob.DefaultBuilder<Unity.Mathematics.double3x2> {}
    public class double3x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double3x2> {}
    public class double3x3Builder : Blob.DefaultBuilder<Unity.Mathematics.double3x3> {}
    public class double3x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double3x3> {}
    public class double3x4Builder : Blob.DefaultBuilder<Unity.Mathematics.double3x4> {}
    public class double3x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double3x4> {}
    public class double4Builder : Blob.DefaultBuilder<Unity.Mathematics.double4> {}
    public class double4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double4> {}
    public class double4x2Builder : Blob.DefaultBuilder<Unity.Mathematics.double4x2> {}
    public class double4x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double4x2> {}
    public class double4x3Builder : Blob.DefaultBuilder<Unity.Mathematics.double4x3> {}
    public class double4x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double4x3> {}
    public class double4x4Builder : Blob.DefaultBuilder<Unity.Mathematics.double4x4> {}
    public class double4x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.double4x4> {}
    public class float2Builder : Blob.DefaultBuilder<Unity.Mathematics.float2> {}
    public class float2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float2> {}
    public class float2x2Builder : Blob.DefaultBuilder<Unity.Mathematics.float2x2> {}
    public class float2x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float2x2> {}
    public class float2x3Builder : Blob.DefaultBuilder<Unity.Mathematics.float2x3> {}
    public class float2x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float2x3> {}
    public class float2x4Builder : Blob.DefaultBuilder<Unity.Mathematics.float2x4> {}
    public class float2x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float2x4> {}
    public class float3Builder : Blob.DefaultBuilder<Unity.Mathematics.float3> {}
    public class float3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float3> {}
    public class float3x2Builder : Blob.DefaultBuilder<Unity.Mathematics.float3x2> {}
    public class float3x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float3x2> {}
    public class float3x3Builder : Blob.DefaultBuilder<Unity.Mathematics.float3x3> {}
    public class float3x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float3x3> {}
    public class float3x4Builder : Blob.DefaultBuilder<Unity.Mathematics.float3x4> {}
    public class float3x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float3x4> {}
    public class float4Builder : Blob.DefaultBuilder<Unity.Mathematics.float4> {}
    public class float4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float4> {}
    public class float4x2Builder : Blob.DefaultBuilder<Unity.Mathematics.float4x2> {}
    public class float4x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float4x2> {}
    public class float4x3Builder : Blob.DefaultBuilder<Unity.Mathematics.float4x3> {}
    public class float4x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float4x3> {}
    public class float4x4Builder : Blob.DefaultBuilder<Unity.Mathematics.float4x4> {}
    public class float4x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.float4x4> {}
    public class halfBuilder : Blob.DefaultBuilder<Unity.Mathematics.half> {}
    public class halfArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.half> {}
    public class half2Builder : Blob.DefaultBuilder<Unity.Mathematics.half2> {}
    public class half2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.half2> {}
    public class half3Builder : Blob.DefaultBuilder<Unity.Mathematics.half3> {}
    public class half3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.half3> {}
    public class half4Builder : Blob.DefaultBuilder<Unity.Mathematics.half4> {}
    public class half4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.half4> {}
    public class int2Builder : Blob.DefaultBuilder<Unity.Mathematics.int2> {}
    public class int2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int2> {}
    public class int2x2Builder : Blob.DefaultBuilder<Unity.Mathematics.int2x2> {}
    public class int2x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int2x2> {}
    public class int2x3Builder : Blob.DefaultBuilder<Unity.Mathematics.int2x3> {}
    public class int2x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int2x3> {}
    public class int2x4Builder : Blob.DefaultBuilder<Unity.Mathematics.int2x4> {}
    public class int2x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int2x4> {}
    public class int3Builder : Blob.DefaultBuilder<Unity.Mathematics.int3> {}
    public class int3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int3> {}
    public class int3x2Builder : Blob.DefaultBuilder<Unity.Mathematics.int3x2> {}
    public class int3x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int3x2> {}
    public class int3x3Builder : Blob.DefaultBuilder<Unity.Mathematics.int3x3> {}
    public class int3x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int3x3> {}
    public class int3x4Builder : Blob.DefaultBuilder<Unity.Mathematics.int3x4> {}
    public class int3x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int3x4> {}
    public class int4Builder : Blob.DefaultBuilder<Unity.Mathematics.int4> {}
    public class int4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int4> {}
    public class int4x2Builder : Blob.DefaultBuilder<Unity.Mathematics.int4x2> {}
    public class int4x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int4x2> {}
    public class int4x3Builder : Blob.DefaultBuilder<Unity.Mathematics.int4x3> {}
    public class int4x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int4x3> {}
    public class int4x4Builder : Blob.DefaultBuilder<Unity.Mathematics.int4x4> {}
    public class int4x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.int4x4> {}
    public class quaternionBuilder : Blob.DefaultBuilder<Unity.Mathematics.quaternion> {}
    public class quaternionArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.quaternion> {}
    public class RandomBuilder : Blob.DefaultBuilder<Unity.Mathematics.Random> {}
    public class RandomArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.Random> {}
    public class RigidTransformBuilder : Blob.DefaultBuilder<Unity.Mathematics.RigidTransform> {}
    public class RigidTransformArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.RigidTransform> {}
    public class uint2Builder : Blob.DefaultBuilder<Unity.Mathematics.uint2> {}
    public class uint2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint2> {}
    public class uint2x2Builder : Blob.DefaultBuilder<Unity.Mathematics.uint2x2> {}
    public class uint2x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint2x2> {}
    public class uint2x3Builder : Blob.DefaultBuilder<Unity.Mathematics.uint2x3> {}
    public class uint2x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint2x3> {}
    public class uint2x4Builder : Blob.DefaultBuilder<Unity.Mathematics.uint2x4> {}
    public class uint2x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint2x4> {}
    public class uint3Builder : Blob.DefaultBuilder<Unity.Mathematics.uint3> {}
    public class uint3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint3> {}
    public class uint3x2Builder : Blob.DefaultBuilder<Unity.Mathematics.uint3x2> {}
    public class uint3x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint3x2> {}
    public class uint3x3Builder : Blob.DefaultBuilder<Unity.Mathematics.uint3x3> {}
    public class uint3x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint3x3> {}
    public class uint3x4Builder : Blob.DefaultBuilder<Unity.Mathematics.uint3x4> {}
    public class uint3x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint3x4> {}
    public class uint4Builder : Blob.DefaultBuilder<Unity.Mathematics.uint4> {}
    public class uint4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint4> {}
    public class uint4x2Builder : Blob.DefaultBuilder<Unity.Mathematics.uint4x2> {}
    public class uint4x2ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint4x2> {}
    public class uint4x3Builder : Blob.DefaultBuilder<Unity.Mathematics.uint4x3> {}
    public class uint4x3ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint4x3> {}
    public class uint4x4Builder : Blob.DefaultBuilder<Unity.Mathematics.uint4x4> {}
    public class uint4x4ArrayBuilder : Blob.ArrayBuilder<Unity.Mathematics.uint4x4> {}

}

#endif

